version: '3.7'
services:
  ensdemo:
    image: intersystems/demo/irishealth/ensdemo:latest
    init: true
    build:
      context: .
      args:
        ARCH: $ARCH
    hostname: ensdemo
    container_name: ensdemo
    ports:
    - "9091:1972"
    - "9092:52773"    
    volumes:
    - type: bind
      source: ./src
      target: /src
    - type: bind
      source: ./shared
      target: /shared
