version: '3.7'
services:
  ensdemo:
    image: store/intersystems/irishealth-community:ensdemo
    init: true
    build:
      context: .
    hostname: ensdemo
    container_name: ensdemo
    ports:
    - "9091:51773"
    - "9092:52773"    
    volumes:
    - type: bind
      source: ./src
      target: /src
    - type: bind
      source: ./shared
      target: /shared