version: '3.7'
services:
  ensdemo:
    build:
      context: .
    hostname: ensdemo
    container_name: ensdemo
    ports:
    - "9091:51773"
    - "9092:52773"
    restart: on-failure
    volumes:
    - type: bind
      source: ./demo
      target: /demo
    - type: bind
      source: ./shared
      target: /shared
    - type: bind
      source: .
      target: /irisdev/app